version: '3.4'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
      - 90:80
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - 3306:3306
      - 33060:3306
    volumes:
      - ./data/db/mysql:/var/lib/mysql
      - ./config/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
